// Seed library data for Prompt Librarian.
// Folder names match the spec; files are realistic, with frontmatter-shape metadata.

const FOLDER_TREE = [
  {
    name: "00-Index",
    path: "00-Index",
    children: [],
  },
  {
    name: "01-Core Transforms",
    path: "01-Core Transforms",
    children: [
      { name: "Transcript Cleanup", path: "01-Core Transforms/Transcript Cleanup", children: [] },
      { name: "Summarization", path: "01-Core Transforms/Summarization", children: [] },
      { name: "Extraction", path: "01-Core Transforms/Extraction", children: [] },
      { name: "Rewrite", path: "01-Core Transforms/Rewrite", children: [] },
    ],
  },
  {
    name: "02-Interview",
    path: "02-Interview",
    children: [
      { name: "Behavioral", path: "02-Interview/Behavioral", children: [] },
      { name: "System Design", path: "02-Interview/System Design", children: [] },
      { name: "Coding", path: "02-Interview/Coding", children: [] },
    ],
  },
  {
    name: "03-Job Search",
    path: "03-Job Search",
    children: [
      { name: "Resume", path: "03-Job Search/Resume", children: [] },
      { name: "Cover Letters", path: "03-Job Search/Cover Letters", children: [] },
      { name: "Outreach", path: "03-Job Search/Outreach", children: [] },
    ],
  },
  {
    name: "04-Product Specs",
    path: "04-Product Specs",
    children: [
      { name: "PRDs", path: "04-Product Specs/PRDs", children: [] },
      { name: "User Stories", path: "04-Product Specs/User Stories", children: [] },
    ],
  },
  {
    name: "05-Research",
    path: "05-Research",
    children: [
      { name: "Literature", path: "05-Research/Literature", children: [] },
      { name: "Competitive", path: "05-Research/Competitive", children: [] },
    ],
  },
  {
    name: "06-Project Prompts",
    path: "06-Project Prompts",
    children: [
      { name: "Career Buddy", path: "06-Project Prompts/Career Buddy", children: [] },
      { name: "OpenClaw", path: "06-Project Prompts/OpenClaw", children: [] },
    ],
  },
  { name: "90-Examples", path: "90-Examples", children: [] },
  { name: "99-Archive", path: "99-Archive", children: [] },
];

// Helpers to generate realistic timestamps.
const _d = (daysAgo, h = 9, m = 0) => {
  const d = new Date(2026, 4, 6, h, m, 0); // anchored "today" = May 6, 2026
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
};

const PROMPTS = [
  // Core transforms — transcript cleanup
  {
    id: "p001",
    filename: "transcript-cleanup-fillers.md",
    folder: "01-Core Transforms/Transcript Cleanup",
    title: "Transcript Cleanup — Remove Fillers",
    category: "Core Transforms",
    subcategory: "Transcript Cleanup",
    function: "transform",
    domain: null,
    project: null,
    tags: ["transcript", "cleanup", "fillers"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(120),
    updated_at: _d(4),
    purpose: "Strip fillers and stutters from a raw transcript while keeping speaker turns and timestamps intact.",
    inputs: "Raw transcript text, optionally with speaker labels and [HH:MM:SS] timestamps.",
    output: "Cleaned transcript in the same format, with fillers removed and minor disfluencies smoothed.",
    body: "You are a careful transcript editor. Remove filler words (um, uh, like, you know, I mean) and false starts. Preserve speaker labels, timestamps, and meaning. Do NOT paraphrase. Do NOT summarize. If a sentence is unintelligible, keep it as [unintelligible] instead of guessing.\n\nReturn the cleaned transcript only.",
    notes: "Best when given <8000 tokens of transcript at a time. Chunk longer ones by speaker turn boundaries.",
    compatibility: "Claude handles long transcripts better. GPT-4 sometimes paraphrases despite instructions — re-emphasize 'do not paraphrase' there.",
    reuseCount: 47,
  },
  {
    id: "p002",
    filename: "transcript-to-bullets.md",
    folder: "01-Core Transforms/Transcript Cleanup",
    title: "Transcript → Bullet Notes",
    category: "Core Transforms",
    subcategory: "Transcript Cleanup",
    function: "summarize",
    tags: ["transcript", "notes", "bullets"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(95),
    updated_at: _d(11),
    purpose: "Convert a meeting or interview transcript into a structured bullet outline with topics and decisions.",
    inputs: "Cleaned transcript.",
    output: "Markdown outline: Topics → sub-bullets, plus 'Decisions' and 'Open questions' sections.",
    body: "Read the transcript. Produce a Markdown outline grouped by topic. Under each topic, capture key points as terse bullets (no full sentences when possible). At the end, add two sections: '## Decisions' and '## Open questions'. Quote speakers only when the exact wording matters.",
    notes: "Pair with transcript-cleanup-fillers.md for best results.",
    compatibility: "",
    reuseCount: 31,
  },
  {
    id: "p003",
    filename: "speaker-diarize-fix.md",
    folder: "01-Core Transforms/Transcript Cleanup",
    title: "Fix Speaker Diarization Mistakes",
    category: "Core Transforms",
    subcategory: "Transcript Cleanup",
    function: "rewrite",
    tags: ["transcript", "diarization"],
    reuse: "medium",
    scope: "reusable",
    created_at: _d(60),
    updated_at: _d(60),
    purpose: "Correct speaker labels in a transcript when diarization mis-attributes turns.",
    inputs: "Transcript with speaker labels, plus a hint about who is who.",
    output: "Same transcript with corrected speaker labels.",
    body: "Given the transcript and the speaker hint, fix speaker labels where context makes the assignment obvious. Do not change the words themselves. If a turn is genuinely ambiguous, leave the label as [?].",
    notes: "",
    compatibility: "",
    reuseCount: 8,
  },

  // Core transforms — summarization
  {
    id: "p004",
    filename: "exec-summary-1pager.md",
    folder: "01-Core Transforms/Summarization",
    title: "Executive Summary (1-Pager)",
    category: "Core Transforms",
    subcategory: "Summarization",
    function: "summarize",
    tags: ["summary", "exec", "1-pager"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(180),
    updated_at: _d(2),
    purpose: "Produce a one-page executive summary with TL;DR, key findings, and recommended actions.",
    inputs: "Long-form document, report, or research notes.",
    output: "Markdown 1-pager: TL;DR (3 lines), Key findings (5 bullets), Recommendations (3 bullets), Risks (2 bullets).",
    body: "Read the source material. Produce a one-page executive summary in this exact structure:\n\n**TL;DR** (3 lines, no bullets)\n**Key findings** (5 bullets, terse)\n**Recommendations** (3 bullets, action-oriented verbs)\n**Risks / unknowns** (2 bullets)\n\nNo preamble. No closing remarks. Markdown only.",
    notes: "Works well for research reports, post-mortems, and design reviews.",
    compatibility: "",
    reuseCount: 88,
  },
  {
    id: "p005",
    filename: "tldr-paragraph.md",
    folder: "01-Core Transforms/Summarization",
    title: "TL;DR — Single Paragraph",
    category: "Core Transforms",
    subcategory: "Summarization",
    function: "summarize",
    tags: ["summary", "tldr"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(150),
    updated_at: _d(20),
    purpose: "Compress any text into a single dense paragraph TL;DR.",
    inputs: "Any text.",
    output: "One paragraph, 60–100 words, no bullets.",
    body: "Compress the input into a single paragraph TL;DR of 60–100 words. Lead with the most important point. No preamble, no headings, no bullets.",
    notes: "",
    compatibility: "",
    reuseCount: 64,
  },
  {
    id: "p006",
    filename: "compare-two-docs.md",
    folder: "01-Core Transforms/Summarization",
    title: "Compare Two Documents",
    category: "Core Transforms",
    subcategory: "Summarization",
    function: "compare",
    tags: ["compare", "diff", "docs"],
    reuse: "medium",
    scope: "reusable",
    created_at: _d(45),
    updated_at: _d(45),
    purpose: "Produce a side-by-side comparison of two documents along stated dimensions.",
    inputs: "Doc A, Doc B, list of dimensions to compare.",
    output: "Markdown table with one row per dimension and columns A, B, Notes.",
    body: "Compare Doc A and Doc B along the given dimensions. Produce a Markdown table:\n\n| Dimension | Doc A | Doc B | Notes |\n\nKeep cells terse. Add a 'Bottom line' sentence below the table.",
    notes: "",
    compatibility: "",
    reuseCount: 12,
  },

  // Core transforms — extraction
  {
    id: "p007",
    filename: "extract-action-items.md",
    folder: "01-Core Transforms/Extraction",
    title: "Extract Action Items",
    category: "Core Transforms",
    subcategory: "Extraction",
    function: "extract",
    tags: ["actions", "todo", "meetings"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(200),
    updated_at: _d(1),
    purpose: "Pull explicit action items from a meeting transcript or notes, with owner and due date when stated.",
    inputs: "Transcript or notes.",
    output: "Markdown list. Each item: '- [ ] <owner> — <action> (<due, if any>)'.",
    body: "Extract only EXPLICIT action items. Do not infer. For each item: owner, action, due date if stated. Format:\n\n- [ ] <owner> — <action> (<due>)\n\nIf owner is unclear, write '?'. If no actions, return 'No action items.'",
    notes: "Run after transcript cleanup for best precision.",
    compatibility: "",
    reuseCount: 102,
  },
  {
    id: "p008",
    filename: "extract-entities-jd.md",
    folder: "01-Core Transforms/Extraction",
    title: "Extract Entities from Job Description",
    category: "Core Transforms",
    subcategory: "Extraction",
    function: "extract",
    tags: ["jobs", "entities", "structured"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(70),
    updated_at: _d(7),
    purpose: "Turn a freeform job description into a structured object: company, role, level, must-haves, nice-to-haves, comp, location.",
    inputs: "Job description text.",
    output: "JSON object with the listed fields.",
    body: "Read the job description and return a JSON object with these fields:\n\n{\n  \"company\": string,\n  \"role\": string,\n  \"level\": string|null,\n  \"location\": string,\n  \"remote\": \"yes\"|\"no\"|\"hybrid\"|null,\n  \"comp\": string|null,\n  \"must_haves\": string[],\n  \"nice_to_haves\": string[],\n  \"red_flags\": string[]\n}\n\nReturn JSON only, no prose.",
    notes: "Pairs with resume-tailor.md.",
    compatibility: "",
    reuseCount: 28,
  },

  // Core transforms — rewrite
  {
    id: "p009",
    filename: "tighten-prose.md",
    folder: "01-Core Transforms/Rewrite",
    title: "Tighten Prose (No Voice Change)",
    category: "Core Transforms",
    subcategory: "Rewrite",
    function: "rewrite",
    tags: ["rewrite", "editing"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(140),
    updated_at: _d(14),
    purpose: "Reduce wordiness while preserving the writer's voice and meaning.",
    inputs: "Draft text.",
    output: "Tightened version of the same text.",
    body: "Tighten the input. Cut filler, redundancy, and hedge words. Keep the writer's voice and rhythm. Do NOT add information. Do NOT change the writer's stance. Return the rewrite only.",
    notes: "Avoid for legal or contractual text.",
    compatibility: "GPT-4 tends to over-edit; emphasize 'preserve voice' explicitly there.",
    reuseCount: 55,
  },

  // Interview
  {
    id: "p010",
    filename: "behavioral-star-coach.md",
    folder: "02-Interview/Behavioral",
    title: "Behavioral STAR Coach",
    category: "Interview",
    subcategory: "Behavioral",
    function: "critique",
    domain: "interview",
    tags: ["star", "behavioral", "coaching"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(110),
    updated_at: _d(3),
    purpose: "Critique a behavioral interview answer against the STAR framework and suggest tightenings.",
    inputs: "The question, the candidate's draft answer.",
    output: "Critique with strengths, gaps in S/T/A/R, and a tightened ~90-second version.",
    body: "You are a senior hiring manager. Critique the candidate's STAR answer.\n\n1. Identify Situation, Task, Action, Result. Flag any missing pillar.\n2. Call out the strongest moment.\n3. Call out the weakest moment.\n4. Provide a tightened ~90-second version preserving the candidate's voice.\n\nBe direct, not encouraging.",
    notes: "Direct tone is intentional — hiring managers don't coddle.",
    compatibility: "",
    reuseCount: 41,
  },
  {
    id: "p011",
    filename: "behavioral-question-bank.md",
    folder: "02-Interview/Behavioral",
    title: "Generate Behavioral Question Bank",
    category: "Interview",
    subcategory: "Behavioral",
    function: "generate",
    domain: "interview",
    tags: ["behavioral", "questions"],
    reuse: "medium",
    scope: "reusable",
    created_at: _d(85),
    updated_at: _d(85),
    purpose: "Generate likely behavioral questions for a given role and seniority.",
    inputs: "Role, level, company values.",
    output: "20 questions grouped by competency.",
    body: "Generate 20 likely behavioral interview questions for the given role and seniority. Group by competency (e.g. ownership, collaboration, ambiguity, conflict, growth). One line per question.",
    notes: "",
    compatibility: "",
    reuseCount: 14,
  },
  {
    id: "p012",
    filename: "system-design-walkthrough.md",
    folder: "02-Interview/System Design",
    title: "System Design Walkthrough Coach",
    category: "Interview",
    subcategory: "System Design",
    function: "critique",
    domain: "interview",
    tags: ["system-design", "architecture", "coaching"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(75),
    updated_at: _d(6),
    purpose: "Walk through a system design problem like an interviewer: probe assumptions, push on bottlenecks, demand tradeoffs.",
    inputs: "Problem statement, candidate's current design.",
    output: "Series of probing questions and direct critique.",
    body: "Act as a staff-level interviewer. Probe the candidate's design with questions about scale assumptions, data model choices, consistency tradeoffs, and failure modes. After 3 rounds of questions, give a direct critique: what's strong, what's missing, what would not pass a real loop.",
    notes: "",
    compatibility: "",
    reuseCount: 22,
  },
  {
    id: "p013",
    filename: "coding-edge-cases.md",
    folder: "02-Interview/Coding",
    title: "Coding — Edge Case Generator",
    category: "Interview",
    subcategory: "Coding",
    function: "generate",
    domain: "interview",
    tags: ["coding", "edge-cases", "testing"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(50),
    updated_at: _d(15),
    purpose: "Given a coding problem, generate the edge cases an interviewer expects you to mention.",
    inputs: "Problem statement.",
    output: "Bulleted list grouped: input boundaries, type/format, scale, concurrency, error paths.",
    body: "Given a coding interview problem, list edge cases grouped under: Input boundaries, Type/format, Scale, Concurrency, Error paths. Be exhaustive but terse.",
    notes: "",
    compatibility: "",
    reuseCount: 19,
  },

  // Job Search
  {
    id: "p014",
    filename: "resume-tailor.md",
    folder: "03-Job Search/Resume",
    title: "Resume Tailor for Specific JD",
    category: "Job Search",
    subcategory: "Resume",
    function: "rewrite",
    domain: "job search",
    tags: ["resume", "jd", "tailoring"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(160),
    updated_at: _d(5),
    purpose: "Rewrite resume bullets to align with a specific job description without inventing experience.",
    inputs: "Resume bullets, job description.",
    output: "Rewritten bullets, one-for-one, plus a 'gaps' section.",
    body: "Rewrite the resume bullets to better match the JD. Keep it factual — do NOT invent skills or outcomes. For each original bullet, return a rewritten version. After the bullets, add '## Gaps' listing JD requirements not covered by the resume.",
    notes: "Always review for fabricated metrics.",
    compatibility: "",
    reuseCount: 73,
  },
  {
    id: "p015",
    filename: "resume-bullet-rewrite.md",
    folder: "03-Job Search/Resume",
    title: "Resume Bullet — Action + Metric",
    category: "Job Search",
    subcategory: "Resume",
    function: "rewrite",
    domain: "job search",
    tags: ["resume", "bullets"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(130),
    updated_at: _d(8),
    purpose: "Rewrite a weak resume bullet into action-verb + scope + metric form.",
    inputs: "One resume bullet.",
    output: "3 candidate rewrites, ranked.",
    body: "Rewrite the bullet into 'action verb + scope + metric or outcome' form. Provide 3 candidates ranked by impact. Do not invent metrics — if metric is missing, mark it [METRIC?].",
    notes: "",
    compatibility: "",
    reuseCount: 39,
  },
  {
    id: "p016",
    filename: "cover-letter-short.md",
    folder: "03-Job Search/Cover Letters",
    title: "Cover Letter — Short, Specific",
    category: "Job Search",
    subcategory: "Cover Letters",
    function: "generate",
    domain: "job search",
    tags: ["cover-letter"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(90),
    updated_at: _d(9),
    purpose: "Draft a 200-word cover letter that names a specific reason for the company and a specific accomplishment.",
    inputs: "JD, resume highlights, one specific reason for the company.",
    output: "200-word cover letter, no clichés.",
    body: "Draft a 200-word cover letter. Open with a specific reason for THIS company (not generic). Body: one accomplishment from the resume that maps to a JD requirement. Close with a one-line ask. No clichés. No 'I am writing to express my interest'.",
    notes: "",
    compatibility: "",
    reuseCount: 26,
  },
  {
    id: "p017",
    filename: "outreach-warm-intro.md",
    folder: "03-Job Search/Outreach",
    title: "Outreach — Warm Intro Request",
    category: "Job Search",
    subcategory: "Outreach",
    function: "generate",
    domain: "job search",
    tags: ["outreach", "intro", "networking"],
    reuse: "medium",
    scope: "reusable",
    created_at: _d(40),
    updated_at: _d(40),
    purpose: "Draft a short note asking a contact for a warm intro to a hiring manager.",
    inputs: "Your name, target company, target person, one line on why.",
    output: "Email draft, <120 words, easy for the contact to forward verbatim.",
    body: "Draft a short outreach message asking a contact for a warm intro. Under 120 words. Include a one-line forwardable blurb the contact can send verbatim. No fluff.",
    notes: "",
    compatibility: "",
    reuseCount: 11,
  },

  // Product Specs
  {
    id: "p018",
    filename: "prd-skeleton.md",
    folder: "04-Product Specs/PRDs",
    title: "PRD Skeleton",
    category: "Product Specs",
    subcategory: "PRDs",
    function: "generate",
    domain: "product specs",
    tags: ["prd", "spec"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(170),
    updated_at: _d(12),
    purpose: "Generate a PRD skeleton from a one-line product idea.",
    inputs: "One-line idea, target user.",
    output: "Markdown PRD: Problem, Users, Goals, Non-goals, Solution, Open questions, Success metrics.",
    body: "From the one-line idea, draft a PRD skeleton with these sections: Problem, Users, Goals, Non-goals, Solution sketch, Open questions, Success metrics. Use bullets. Mark unknowns explicitly with [TBD: …].",
    notes: "",
    compatibility: "",
    reuseCount: 34,
  },
  {
    id: "p019",
    filename: "prd-critique.md",
    folder: "04-Product Specs/PRDs",
    title: "PRD Critique — Senior PM",
    category: "Product Specs",
    subcategory: "PRDs",
    function: "critique",
    domain: "product specs",
    tags: ["prd", "critique"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(100),
    updated_at: _d(10),
    purpose: "Critique a draft PRD as a senior PM would: missing users, fuzzy success metrics, hidden assumptions.",
    inputs: "Draft PRD.",
    output: "Critique with concrete revision asks.",
    body: "You are a senior PM. Critique the draft PRD. Call out: unclear users, fuzzy success metrics, hidden assumptions, scope risks, missing non-goals. End with the top 3 things to fix before review.",
    notes: "",
    compatibility: "",
    reuseCount: 25,
  },
  {
    id: "p020",
    filename: "user-story-from-spec.md",
    folder: "04-Product Specs/User Stories",
    title: "User Stories from Spec",
    category: "Product Specs",
    subcategory: "User Stories",
    function: "transform",
    domain: "product specs",
    tags: ["stories", "agile"],
    reuse: "medium",
    scope: "reusable",
    created_at: _d(65),
    updated_at: _d(65),
    purpose: "Convert a spec into a user-story backlog with acceptance criteria.",
    inputs: "Spec text.",
    output: "Markdown list: 'As a <user>, I want <X> so that <Y>' + acceptance criteria per story.",
    body: "From the spec, produce user stories. Format: 'As a <user>, I want <X>, so that <Y>.' Under each, list acceptance criteria as Given/When/Then. Group by epic.",
    notes: "",
    compatibility: "",
    reuseCount: 9,
  },

  // Research
  {
    id: "p021",
    filename: "lit-review-skim.md",
    folder: "05-Research/Literature",
    title: "Literature Skim",
    category: "Research",
    subcategory: "Literature",
    function: "summarize",
    domain: "research",
    tags: ["research", "literature"],
    reuse: "high",
    scope: "reusable",
    created_at: _d(115),
    updated_at: _d(13),
    purpose: "Skim a paper into a structured note: claim, method, evidence, limitations, relevance.",
    inputs: "Paper text or abstract.",
    output: "Structured note with the 5 sections.",
    body: "Skim the paper. Produce a note with these sections (each terse, 2–4 lines):\n\n- Claim\n- Method\n- Evidence\n- Limitations\n- Relevance to my work",
    notes: "Add your project context to the prompt to shape the 'Relevance' section.",
    compatibility: "",
    reuseCount: 38,
  },
  {
    id: "p022",
    filename: "competitive-positioning.md",
    folder: "05-Research/Competitive",
    title: "Competitive Positioning Map",
    category: "Research",
    subcategory: "Competitive",
    function: "compare",
    domain: "research",
    tags: ["competitive", "positioning"],
    reuse: "medium",
    scope: "reusable",
    created_at: _d(55),
    updated_at: _d(55),
    purpose: "Produce a 2x2 positioning map and a feature matrix from competitor descriptions.",
    inputs: "Competitor names + descriptions, two axes.",
    output: "ASCII 2x2 + Markdown feature matrix.",
    body: "Given the competitors and the two axes, place each on a 2x2 (use ASCII) and produce a feature matrix as a Markdown table. End with a one-line 'gap' observation.",
    notes: "",
    compatibility: "",
    reuseCount: 7,
  },

  // Project — Career Buddy
  {
    id: "p023",
    filename: "cb-onboarding-coach.md",
    folder: "06-Project Prompts/Career Buddy",
    title: "Career Buddy — Onboarding Coach",
    category: "Project Prompts",
    subcategory: "Career Buddy",
    function: "generate",
    project: "Career Buddy",
    tags: ["career-buddy", "onboarding"],
    reuse: "high",
    scope: "project reusable",
    created_at: _d(80),
    updated_at: _d(2),
    purpose: "System prompt for Career Buddy's onboarding flow that elicits goals, constraints, and timeline.",
    inputs: "User's free-text intro.",
    output: "Conversational follow-up that gathers: target role, timeline, constraints, current resume state.",
    body: "You are Career Buddy's onboarding coach. Goal: elicit target role, timeline, geographic/remote constraints, comp expectations, and current resume state. Ask one question at a time. Reflect back what you've learned at the end and confirm before moving on.",
    notes: "Keep questions ≤ 2 sentences each. Avoid asking for everything at once.",
    compatibility: "",
    reuseCount: 18,
  },
  {
    id: "p024",
    filename: "cb-weekly-checkin.md",
    folder: "06-Project Prompts/Career Buddy",
    title: "Career Buddy — Weekly Check-in",
    category: "Project Prompts",
    subcategory: "Career Buddy",
    function: "generate",
    project: "Career Buddy",
    tags: ["career-buddy", "checkin"],
    reuse: "high",
    scope: "project reusable",
    created_at: _d(35),
    updated_at: _d(0),
    purpose: "Weekly check-in script: applications sent, responses, blockers, next-week plan.",
    inputs: "User's free-text update or stored history.",
    output: "Markdown summary + 3 concrete actions for the next week.",
    body: "Run a weekly check-in. Ask: applications sent this week, responses received, blockers. Produce a Markdown summary with counts and a 'Next week' section listing 3 concrete actions.",
    notes: "",
    compatibility: "",
    reuseCount: 13,
  },
  {
    id: "p025",
    filename: "cb-mock-interview.md",
    folder: "06-Project Prompts/Career Buddy",
    title: "Career Buddy — Mock Interview",
    category: "Project Prompts",
    subcategory: "Career Buddy",
    function: "generate",
    project: "Career Buddy",
    tags: ["career-buddy", "mock", "interview"],
    reuse: "medium",
    scope: "project reusable",
    created_at: _d(25),
    updated_at: _d(25),
    purpose: "Run a mock behavioral interview with realistic follow-ups, then critique.",
    inputs: "Target role, level.",
    output: "Q&A transcript followed by structured critique.",
    body: "Conduct a mock behavioral interview for the given role/level. Ask 5 questions one at a time, with at least one follow-up per answer. After the 5th, produce a structured critique using the STAR framework.",
    notes: "",
    compatibility: "",
    reuseCount: 6,
  },

  // Project — OpenClaw
  {
    id: "p026",
    filename: "oc-bug-triage.md",
    folder: "06-Project Prompts/OpenClaw",
    title: "OpenClaw — Bug Triage",
    category: "Project Prompts",
    subcategory: "OpenClaw",
    function: "classify",
    project: "OpenClaw",
    tags: ["openclaw", "triage", "bugs"],
    reuse: "high",
    scope: "project reusable",
    created_at: _d(70),
    updated_at: _d(7),
    purpose: "Classify incoming OpenClaw bug reports by severity, area, and likely root cause.",
    inputs: "Raw bug report text.",
    output: "JSON: { severity, area, likely_cause, missing_info[] }.",
    body: "Triage the bug report. Return JSON:\n\n{\n  \"severity\": \"S0\"|\"S1\"|\"S2\"|\"S3\",\n  \"area\": string,\n  \"likely_cause\": string,\n  \"missing_info\": string[]\n}\n\nIf the report lacks repro steps, list 'repro_steps' in missing_info.",
    notes: "Severity scale: S0=outage, S1=major, S2=minor, S3=cosmetic.",
    compatibility: "",
    reuseCount: 21,
  },
  {
    id: "p027",
    filename: "oc-release-notes.md",
    folder: "06-Project Prompts/OpenClaw",
    title: "OpenClaw — Release Notes from PRs",
    category: "Project Prompts",
    subcategory: "OpenClaw",
    function: "transform",
    project: "OpenClaw",
    tags: ["openclaw", "release-notes"],
    reuse: "high",
    scope: "project reusable",
    created_at: _d(30),
    updated_at: _d(4),
    purpose: "Turn a list of merged PR titles into user-facing release notes.",
    inputs: "List of PR titles + descriptions.",
    output: "Markdown release notes with sections: Highlights, Improvements, Fixes.",
    body: "Convert the PR list into release notes. Sections: Highlights (top 3 user-visible), Improvements, Fixes. Phrase from the user's perspective, not the developer's. Skip internal refactors unless they affect users.",
    notes: "",
    compatibility: "",
    reuseCount: 16,
  },
  {
    id: "p028",
    filename: "oc-config-explainer.md",
    folder: "06-Project Prompts/OpenClaw",
    title: "OpenClaw — Config Explainer",
    category: "Project Prompts",
    subcategory: "OpenClaw",
    function: "transform",
    project: "OpenClaw",
    tags: ["openclaw", "config", "docs"],
    reuse: "medium",
    scope: "project reusable",
    created_at: _d(20),
    updated_at: _d(20),
    purpose: "Explain an OpenClaw config block in plain English with a 'when to change it' note.",
    inputs: "YAML config block.",
    output: "Per-key plain-English explanation + 'change when' guidance.",
    body: "For each key in the config, give a plain-English one-liner and a 'change when …' guidance line. Skip keys that are self-explanatory (e.g. 'name').",
    notes: "",
    compatibility: "",
    reuseCount: 5,
  },

  // Examples
  {
    id: "p029",
    filename: "example-style-guide.md",
    folder: "90-Examples",
    title: "Example — Style Guide Reference",
    category: "Examples",
    subcategory: null,
    function: "generate",
    tags: ["example", "style"],
    reuse: "low",
    scope: "reusable",
    created_at: _d(220),
    updated_at: _d(220),
    purpose: "Reference example showing the prompt file shape.",
    inputs: "—",
    output: "—",
    body: "(reference file)",
    notes: "",
    compatibility: "",
    reuseCount: 2,
  },
  {
    id: "p030",
    filename: "example-bad-vague.md",
    folder: "90-Examples",
    title: "Example — Bad Prompt (Vague)",
    category: "Examples",
    subcategory: null,
    function: "generate",
    tags: ["example", "anti-pattern"],
    reuse: "low",
    scope: "one-off",
    created_at: _d(210),
    updated_at: _d(210),
    purpose: "An anti-pattern example: prompt is too vague.",
    inputs: "",
    output: "",
    body: "Make this better.",
    notes: "Kept as a teaching example. Notice no purpose, no inputs, no output spec.",
    compatibility: "",
    reuseCount: 0,
  },

  // Index
  {
    id: "p031",
    filename: "README.md",
    folder: "00-Index",
    title: "Library README",
    category: "Index",
    subcategory: null,
    function: null,
    tags: ["index", "readme"],
    reuse: "low",
    scope: "reusable",
    created_at: _d(220),
    updated_at: _d(15),
    purpose: "Overview of how the library is organized.",
    inputs: "—",
    output: "—",
    body: "# Prompt Library\n\nOrganized by **function**, then **domain**, then **project**.\n\nNever organized by LLM vendor.\n\nSee 90-Examples for shape reference.",
    notes: "",
    compatibility: "",
    reuseCount: 1,
  },

  // Recently captured / messy ones for "needs metadata" hygiene view
  {
    id: "p032",
    filename: "untitled-2026-05-04.md",
    folder: "00-Index",
    title: "Untitled (paste)",
    category: null,
    subcategory: null,
    function: null,
    tags: [],
    reuse: null,
    scope: null,
    created_at: _d(2),
    updated_at: _d(2),
    purpose: "",
    inputs: "",
    output: "",
    body: "Help me write a thing for the customer thing about the launch — needs to be short and hit the three points we discussed.",
    notes: "",
    compatibility: "",
    reuseCount: 0,
    needsTriage: true,
  },
  {
    id: "p033",
    filename: "archive-old-resume-rewriter.md",
    folder: "99-Archive",
    title: "[ARCHIVED] Old Resume Rewriter v1",
    category: "Job Search",
    subcategory: "Resume",
    function: "rewrite",
    domain: "job search",
    tags: ["resume", "archived"],
    reuse: "low",
    scope: "reusable",
    created_at: _d(300),
    updated_at: _d(140),
    purpose: "Superseded by resume-tailor.md. Kept for reference.",
    inputs: "—",
    output: "—",
    body: "(archived)",
    notes: "Archived 2026-01-16. Use resume-tailor.md instead.",
    compatibility: "",
    reuseCount: 0,
  },
];

// Export to window for cross-script use.
window.FOLDER_TREE = FOLDER_TREE;
window.PROMPTS = PROMPTS;
